language: python
python:
- '3.6'
install:
- pip install -r twote_requirements.txt
- echo "import nltk; nltk.download('punkt')" | python manage.py shell
script:
- python manage.py test openspaces/bot_utils/
- python manage.py test openspaces/tests/
before_install:
