language: python
python:
- '3.6'
install:
- pip install -r twote_requirements.txt
- echo "import nltk; nltk.download('punkt')" | python manage.py shell
script:
- python manage.py test openspaces/bot_utils/
- python manage.py test openspaces/tests/
before_install:
- openssl aes-256-cbc -K $encrypted_9a2b31df230e_key -iv $encrypted_9a2b31df230e_iv
  -in secrets.tar.enc -out secrets.tar -d
