nguage: python
python:
- '3.6'
install:
- pip install -r twote_requirements.txt
- echo "import nltk; nltk.download('punkt')" | python manage.py shell
script:
- python manage.py test twote/bot_utils/
before_install:
